language: go

install:
 - go get github.com/dustin/go-humanize
 - go get github.com/onsi/gomega
 - go get github.com/onsi/ginkgo
 - go get code.google.com/p/go.tools/cmd/cover
 - go install src/github.com/CapillarySoftware/goiostat/iostat.go
 - export PATH=$PATH:$HOME/gopath/bin

script: bin/run_tests_travis.sh
