---

- name: apply go to all servers
  hosts: all
  user: root
  
  tasks: 
  - name: install deps
    yum: name=mercurial,git state=latest
  - name: clone git
    sudo: true
    sudo_user: capillaryDeploy
    git: repo=git@github.com:CapillarySoftware/goiostat.git dest=/home/capillaryDeploy/go/src/github.com/CapillarySoftware/goiostat accept_hostkey=yes version=master

  - name: install goiostat
    command: ./install.sh chdir=/home/capillaryDeploy/go/src/github.com/CapillarySoftware/goiostat/
