---

- name: apply go to all servers
  hosts: all
  user: root
  vars:
    env:
      GOPATH: /home/capillaryDeploy/go 
  tasks: 
  - name: install deps
    yum: name=mercurial,git state=latest

#  - name: clone git
#    sudo: true
#    sudo_user: capillaryDeploy
#    git: repo=git@github.com:CapillarySoftware/goiostat.git 
#         dest=/home/capillaryDeploy/go/src/github.com/CapillarySoftware/goiostat 
#         accept_hostkey=yes 
#         version=master
  - debug: msg={{ ansible_env.GOPATH }}
  
  - name: change gopath 
    shell: export GOPATH=/home/capillaryDeploy/go

  - name: install goiostat
    sudo: true sudo_flags=
    sudo_user: capillaryDeploy
    shell: ./install.sh 
           chdir=/home/capillaryDeploy/go/src/github.com/CapillarySoftware/goiostat
